### ISSUE TITLE
Footer graphic looks like butt

### ISSUE THREAD

**Issue by rejon** [waiting4bassel/waiting4bassel.cc#11]
maybe jsut remove or create some outlines or something more sharp

**Comment by christopheradams** [comment]
How about now with the SVG?

**Comment by rejon** [comment]
yes, much better but wish there was more padding around the "Waiting"

On Tue, Dec 15, 2015 at 5:34 PM, Christopher Adams <notifications@github.com

**Comment by christopheradams** [comment]
ok ed532d4

**Comment by rejon** [comment]
Yeah, I think just remove it altogether. ON mobile it is weird behind the graphics. Better just white.

**Comment by christopheradams** [comment]
ok
