### ISSUE TITLE
Conflicting copyright/license notices

### ISSUE THREAD

**Issue by mlinksva** [waiting4bassel/waiting4bassel.cc#19]
* waiting4bassel.cc footer: CC0-1.0
* CC "open store" and Lulu: CC-BY-2.5
* epub: raw copyright notices

It'd be nice if they all stated the same thing, preferably the first. :smile:

**Comment by rejon** [comment]
Yeah, this is embarrasing.

**Comment by rejon** [comment]
On the lulu side, they might not offer cc zero. Their site is down for maintenance right now, but should be brought up with them.

The book one needs investigation.

Everything should be CC ZERO across the board.

**Comment by christopheradams** [comment]
CC0 is not a drop-down option on Lulu, but I did just notice you can enter in a custom license. I'll fix it the next time I push a revision to the book.

**Comment by rejon** [comment]
That's great!

**Comment by christopheradams** [comment]
This is fixed now.
