### ISSUE TITLE
pagination problems in the english version

### ISSUE THREAD

**Issue by rejon** [waiting4bassel/waiting4bassel.cc#21]
Reviewer feedback: "Finally, there are some pagination and punctuation problems in the English version. I wasn't sure if that is just because this is a reading copy, or if they would carry over into the retail version."

**Comment by christopheradams** [comment]
Need more details. Also this issue should be filed at https://github.com/waiting4bassel/waiting-gitbook/issues

**Comment by christopheradams** [comment]
Ok, I think this refers to what was mentioned in issue #22
