### ISSUE TITLE
suggested typo grammar corrections from reviewer

### ISSUE THREAD

**Issue by rejon** [waiting4bassel/waiting4bassel.cc#22]
- p. 3 about.
 
“Waiting…is a prose book…”
 
is it not a poetry book, rather than a prose book?
 
- p. 7
 
“a family affair’s warm collaboration”
 
may wish to delete "affair," as this is unclear in context.
 
- p. 12
 
looks like the closing quotation mark is missing
 
- p. 30-31
 
Single line overflow…can probably be corrected with a little adjustment
 
- p. 33
 
Possibly a missing line between stanzas and a missing period at the end of the second stanza
 
- p. 34-35
 
Single line overflow….can probably be corrected
 
- p. 37
 
Capitalization missing from last two lines in first stanza

**Comment by christopheradams** [comment]
These issues should really be filed at
https://github.com/waiting4bassel/waiting-gitbook/issues, and not the
repo for the website.

On 01/15/2016 10:18 AM, Jon Phillips wrote:
>   * p. 3 about.
> 
> “Waiting…is a prose book…”
> 
> is it not a poetry book, rather than a prose book?

Noura wanted it this way. Not second-guessing.

>   * p. 7
> 
> “a family affair’s warm collaboration”
> 
> may wish to delete "affair," as this is unclear in context.

Fixed

>   * p. 12
> 
> looks like the closing quotation mark is missing

Fixed

>   * p. 30-31
> 
> Single line overflow…can probably be corrected with a little adjustment

Won't fix. This only affects the reading copy.

>   * p. 33
> 
> Possibly a missing line between stanzas and a missing period at the end
> of the second stanza

Fixed. There's no missing line. Removed the unnecessary blank line.

>   * p. 34-35
> 
> Single line overflow….can probably be corrected

Won't fix.

>   * p. 37
> 
> Capitalization missing from last two lines in first stanza

Fixed.
